//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeX2img.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeX2img.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add template に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ADD_TEMPLATEMSG {
            get {
                return ResourceManager.GetString("ADD_TEMPLATEMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All pages are empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ALLPAGE_EMPTYMSG {
            get {
                return ResourceManager.GetString("ALLPAGE_EMPTYMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parsing of the source file failed.
        ///Please check \\begin{document}, \\end{document} etc. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ANALYZESOURCEERROR {
            get {
                return ResourceManager.GetString("ANALYZESOURCEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot write
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AUTHORIZEDERROR {
            get {
                return ResourceManager.GetString("AUTHORIZEDERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bold に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BOLD {
            get {
                return ResourceManager.GetString("BOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to open the working folder {0}, please check TMP and TEMP. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CANNOT_OPEN_WORKDIR {
            get {
                return ResourceManager.GetString("CANNOT_OPEN_WORKDIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the current preamble to the following:
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CHANGE_CURRENTPREAMBLE {
            get {
                return ResourceManager.GetString("CHANGE_CURRENTPREAMBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The current character code is {0}, but the file seems to be with {1}. Do you want to use {0}? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CHECK_ENCODEMSG {
            get {
                return ResourceManager.GetString("CHECK_ENCODEMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delay of animation (sec) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_ANIMATION_DELAY {
            get {
                return ResourceManager.GetString("CMDLINE_ANIMATION_DELAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loop count of animation (0 =infinity) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_ANIMATION_LOOP {
            get {
                return ResourceManager.GetString("CMDLINE_ANIMATION_LOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anti-aliasing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_ANTIALIAS {
            get {
                return ResourceManager.GetString("CMDLINE_ANTIALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background color (ex: FF0000, red, &quot;255 0 0&quot;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_BACKGROUND_COLOR {
            get {
                return ResourceManager.GetString("CMDLINE_BACKGROUND_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Batch mode (stop/nonstop) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_BATCH {
            get {
                return ResourceManager.GetString("CMDLINE_BATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom margin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_BOTTOM_MARGIN {
            get {
                return ResourceManager.GetString("CMDLINE_BOTTOM_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy generated files to the clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_COPY_TO_CLIPBOARD {
            get {
                return ResourceManager.GetString("CMDLINE_COPY_TO_CLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove &lt;width&gt; and &lt;height&gt; (SVG(Z)) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_DELETE_DISPLAY_SIZE {
            get {
                return ResourceManager.GetString("CMDLINE_DELETE_DISPLAY_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete temporary files after compiling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_DELETE_TMPFILES {
            get {
                return ResourceManager.GetString("CMDLINE_DELETE_TMPFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set path for dvi driver に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_DVIDRIVER {
            get {
                return ResourceManager.GetString("CMDLINE_DVIDRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Embed the source in output image files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_EMBED_SOURCE {
            get {
                return ResourceManager.GetString("CMDLINE_EMBED_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify stop or nonstop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_ERROR_INVALID_BATCHTYPE {
            get {
                return ResourceManager.GetString("CMDLINE_ERROR_INVALID_BATCHTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unrecognized margin specification. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_ERROR_INVALID_MARGIN {
            get {
                return ResourceManager.GetString("CMDLINE_ERROR_INVALID_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time out period should be greater than zero. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_ERROR_INVALID_TIMEOUT {
            get {
                return ResourceManager.GetString("CMDLINE_ERROR_INVALID_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify bp or bx. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_ERROR_INVALID_UNIT {
            get {
                return ResourceManager.GetString("CMDLINE_ERROR_INVALID_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save settings and exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_EXIT {
            get {
                return ResourceManager.GetString("CMDLINE_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set path for Ghostscript に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_GS {
            get {
                return ResourceManager.GetString("CMDLINE_GS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guess compile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_GUESS_COMPILE {
            get {
                return ResourceManager.GetString("CMDLINE_GUESS_COMPILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show this message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_HELP {
            get {
                return ResourceManager.GetString("CMDLINE_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Current: {0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_HELP_CURRENT {
            get {
                return ResourceManager.GetString("CMDLINE_HELP_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Force conversion by ignoring nonfatal errors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_IGNORE_ERRORS {
            get {
                return ResourceManager.GetString("CMDLINE_IGNORE_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character code (utf8/sjis/jis/euc/no) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_KANJI {
            get {
                return ResourceManager.GetString("CMDLINE_KANJI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keep the original page size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_KEEP_PAGE_SIZE {
            get {
                return ResourceManager.GetString("CMDLINE_KEEP_PAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set path for latex に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_LATEX {
            get {
                return ResourceManager.GetString("CMDLINE_LATEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left margin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_LEFT_MARGIN {
            get {
                return ResourceManager.GetString("CMDLINE_LEFT_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load default settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_LOAD_DEFAULTS {
            get {
                return ResourceManager.GetString("CMDLINE_LOAD_DEFAULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate images with low resolution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_LOW_RESOLUTION {
            get {
                return ResourceManager.GetString("CMDLINE_LOW_RESOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Margins (all / leftright topbottom / left top right bottom) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_MARGINS {
            get {
                return ResourceManager.GetString("CMDLINE_MARGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make a single file (PDF / TIFF /SVG(Z)) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_MERGE_OUTPUT_FILES {
            get {
                return ResourceManager.GetString("CMDLINE_MERGE_OUTPUT_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (maximum) number of times for LaTeX に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_NUM {
            get {
                return ResourceManager.GetString("CMDLINE_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ghostscript is before version 9.14 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_OLDGS {
            get {
                return ResourceManager.GetString("CMDLINE_OLDGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set path for pdfTeX に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_PDFTEX {
            get {
                return ResourceManager.GetString("CMDLINE_PDFTEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview after compiling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_PREVIEW {
            get {
                return ResourceManager.GetString("CMDLINE_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quiet mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_QUIET {
            get {
                return ResourceManager.GetString("CMDLINE_QUIET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resolution level に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_RESOLUTION {
            get {
                return ResourceManager.GetString("CMDLINE_RESOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right margin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_RIGHT_MARGIN {
            get {
                return ResourceManager.GetString("CMDLINE_RIGHT_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_SAVESETTINGS {
            get {
                return ResourceManager.GetString("CMDLINE_SAVESETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time out period (seconds) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_TIMEOUT {
            get {
                return ResourceManager.GetString("CMDLINE_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top margin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_TOP_MARGIN {
            get {
                return ResourceManager.GetString("CMDLINE_TOP_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transparent に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_TRANSPARENT {
            get {
                return ResourceManager.GetString("CMDLINE_TRANSPARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unit of margins ( bp/px ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_UNIT {
            get {
                return ResourceManager.GetString("CMDLINE_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show version information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_VERSION {
            get {
                return ResourceManager.GetString("CMDLINE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keep original text information (PDF / SVG(Z)) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_WITH_TEXT {
            get {
                return ResourceManager.GetString("CMDLINE_WITH_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Working folder (tmp/file/current) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CMDLINE_WORKINGDIR {
            get {
                return ResourceManager.GetString("CMDLINE_WORKINGDIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compiling TeX source に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPILE_TEX {
            get {
                return ResourceManager.GetString("COMPILE_TEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The extension of the output file is {0} but the extension of the file type you required is {1}. Choose the extension you want to use. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFLICT_EXTENSION_MESSAGE {
            get {
                return ResourceManager.GetString("CONFLICT_EXTENSION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We skip a preprocessing for emf file because it failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DASHTOLINE_FAIL_MSG {
            get {
                return ResourceManager.GetString("DASHTOLINE_FAIL_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete {0}? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DELETEMSG {
            get {
                return ResourceManager.GetString("DELETEMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following paths are suggested as a suitable to the template. Do you want to change?{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DETECT_RECOMMENDED_PATH {
            get {
                return ResourceManager.GetString("DETECT_RECOMMENDED_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error is detected. Please retry.
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DETECTERROR {
            get {
                return ResourceManager.GetString("DETECTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DVI To PDF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DVITOPDF {
            get {
                return ResourceManager.GetString("DVITOPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Embedding the source code is only supported with the NTFS file system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMBED_IS_ONLY_NTFS {
            get {
                return ResourceManager.GetString("EMBED_IS_ONLY_NTFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The page {0} is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMPTYMSG {
            get {
                return ResourceManager.GetString("EMPTYMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EPS To PDF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EPSTOPDF {
            get {
                return ResourceManager.GetString("EPSTOPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute Ghostscript に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EXEC_GS {
            get {
                return ResourceManager.GetString("EXEC_GS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute mudraw に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EXEC_MUDRAW {
            get {
                return ResourceManager.GetString("EXEC_MUDRAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute pdfiumdraw に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EXEC_PDFIUMDRAW {
            get {
                return ResourceManager.GetString("EXEC_PDFIUMDRAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute pdftex に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EXEC_PDFTEX {
            get {
                return ResourceManager.GetString("EXEC_PDFTEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to concatinate images. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FAIL_CONCAT_IMAGES {
            get {
                return ResourceManager.GetString("FAIL_CONCAT_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to get boundingbox. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FAIL_GETBOUNDINGBOX {
            get {
                return ResourceManager.GetString("FAIL_GETBOUNDINGBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to guess {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FAIL_GUESS {
            get {
                return ResourceManager.GetString("FAIL_GUESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Faile to guess paths of LaTeX / DVI driver / Ghostscript. Please set them manually. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FAIL_INIT_PATH {
            get {
                return ResourceManager.GetString("FAIL_INIT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot open {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FAIL_OPEN {
            get {
                return ResourceManager.GetString("FAIL_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to get total pdf pages. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FAIL_PDFPAGES {
            get {
                return ResourceManager.GetString("FAIL_PDFPAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to make a temporary file. Please check the folder
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FAIL_TMPFILE {
            get {
                return ResourceManager.GetString("FAIL_TMPFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to make a temporary folder
        ///{0}
        ///Please check TMP and TEMP. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FAIL_TMPFOLDER {
            get {
                return ResourceManager.GetString("FAIL_TMPFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FAILED {
            get {
                return ResourceManager.GetString("FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is taking a long time for {0}.
        ///The program may be freezing. Do you want to continue?
        ///If it is not continued, it will be killed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FREEZMSG {
            get {
                return ResourceManager.GetString("FREEZMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to generate the image. Please check the source code. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GENERATEERROR {
            get {
                return ResourceManager.GetString("GENERATEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get BoundingBox に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GET_BOUNDINGBOX {
            get {
                return ResourceManager.GetString("GET_BOUNDINGBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some errors are ignored.
        ///The result might be not as expected.
        ///Check the source again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IGNOREDERRORWARNING {
            get {
                return ResourceManager.GetString("IGNOREDERRORWARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TeX source (*.tex)|*.tex|Image files ({0})|{1}|All files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IMPORTDIALOG_FILTER {
            get {
                return ResourceManager.GetString("IMPORTDIALOG_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to replace the current preamble and source with the imported file? The current preamble and the source will be remoevd. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IMPORTMSG {
            get {
                return ResourceManager.GetString("IMPORTMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set paths as
        ///{0}
        ///{1}
        ///{2}
        ///{3}
        ///If they are not correct, please set them manually. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INIT_PATH {
            get {
                return ResourceManager.GetString("INIT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input the name of the template. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INPUTE_TEMPLATE_NAME {
            get {
                return ResourceManager.GetString("INPUTE_TEMPLATE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid color name: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INVALID_COLOR_NAME {
            get {
                return ResourceManager.GetString("INVALID_COLOR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: Invalid extension. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INVALID_EXTENSION {
            get {
                return ResourceManager.GetString("INVALID_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INVALID_INPUT {
            get {
                return ResourceManager.GetString("INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The input to the option {0} is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INVALID_INPUT_TO_OPTION {
            get {
                return ResourceManager.GetString("INVALID_INPUT_TO_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] is not used as the name of a template. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INVALID_TEMPLATE_NAME {
            get {
                return ResourceManager.GetString("INVALID_TEMPLATE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generating Failed because {0} is opened by another application.{1} Please close the application and retry. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IOERROR {
            get {
                return ResourceManager.GetString("IOERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Italic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ITALIC {
            get {
                return ResourceManager.GetString("ITALIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Managing templates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MANAGE_TEMPLATES {
            get {
                return ResourceManager.GetString("MANAGE_TEMPLATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you mean a option name? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MAY_BE_OPTION {
            get {
                return ResourceManager.GetString("MAY_BE_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The source file is not embedded in {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NO_EMBEDDED_SOURCE {
            get {
                return ResourceManager.GetString("NO_EMBEDDED_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No argument. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOARGUMENT {
            get {
                return ResourceManager.GetString("NOARGUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No input file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOINPUTFILE {
            get {
                return ResourceManager.GetString("NOINPUTFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No input file for {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOOUTPUT_FILE {
            get {
                return ResourceManager.GetString("NOOUTPUT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Since the following files are not found, TeX2img cannot executed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOSYSTEMFILE {
            get {
                return ResourceManager.GetString("NOSYSTEMFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   no (input: {0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOT_SPECIFY_ENCODE {
            get {
                return ResourceManager.GetString("NOT_SPECIFY_ENCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOTEXIST {
            get {
                return ResourceManager.GetString("NOTEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1} is needed for {0}, put {1} in tool path directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOTOOLERROR {
            get {
                return ResourceManager.GetString("NOTOOLERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chose from {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOTPOSSIBLEARG {
            get {
                return ResourceManager.GetString("NOTPOSSIBLEARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a template to delete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOTSELECTED_DELETETEMPLATE {
            get {
                return ResourceManager.GetString("NOTSELECTED_DELETETEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a template to show. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOTSELECTED_SHOWTEMPLATE {
            get {
                return ResourceManager.GetString("NOTSELECTED_SHOWTEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a template name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOTSELECTED_TEMPLATE {
            get {
                return ResourceManager.GetString("NOTSELECTED_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This function can be used only with the direct input mode. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ONLY_INPUTMODE {
            get {
                return ResourceManager.GetString("ONLY_INPUTMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} exists. Do you wan to overwrite? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OVERWRITEMSG {
            get {
                return ResourceManager.GetString("OVERWRITEMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to overwrite the template {0} with the current preamble? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OVERWRITETEMPLATEMSG {
            get {
                return ResourceManager.GetString("OVERWRITETEMPLATEMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot execute {0}.
        ///Check the path of {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PATHERROR {
            get {
                return ResourceManager.GetString("PATHERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDF To EPS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PDFTOEPS {
            get {
                return ResourceManager.GetString("PDFTOEPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PS To PDF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PSTOPDF {
            get {
                return ResourceManager.GetString("PSTOPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input y or n. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PUSHYORN {
            get {
                return ResourceManager.GetString("PUSHYORN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you wan to restore the templates {0} and remove other templates? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RESTORETEMPLATE_COMPLETEMSG {
            get {
                return ResourceManager.GetString("RESTORETEMPLATE_COMPLETEMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you wan to restore the templates {0}? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RESTORETEMPLATEMSG {
            get {
                return ResourceManager.GetString("RESTORETEMPLATEMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SAMPLE {
            get {
                return ResourceManager.GetString("SAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save the current preamble に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SAVE_CURRENT_PREAMBLE {
            get {
                return ResourceManager.GetString("SAVE_CURRENT_PREAMBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SECONDS {
            get {
                return ResourceManager.GetString("SECONDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   See help via {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SEEHELPMSG {
            get {
                return ResourceManager.GetString("SEEHELPMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The template {0} is:
        ///
        ///{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SHOWTEMPLATEMSG {
            get {
                return ResourceManager.GetString("SHOWTEMPLATEMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The page {0} is skipped because it is empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SKIPPED_BACAUSE_EMPTY {
            get {
                return ResourceManager.GetString("SKIPPED_BACAUSE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STOP {
            get {
                return ResourceManager.GetString("STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop converting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STOPCONVERTMSG {
            get {
                return ResourceManager.GetString("STOPCONVERTMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TeX distribution ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TEX_DISTRIBUTION {
            get {
                return ResourceManager.GetString("TEX_DISTRIBUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap TeX2img_64x64 {
            get {
                object obj = ResourceManager.GetObject("TeX2img_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Failed to execute {0}.
        ///Don&apos;t delete the folder {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOLERROR {
            get {
                return ResourceManager.GetString("TOOLERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transparent に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TRANSPARENT {
            get {
                return ResourceManager.GetString("TRANSPARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Usage:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string USAGE {
            get {
                return ResourceManager.GetString("USAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   White に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WHITE {
            get {
                return ResourceManager.GetString("WHITE", resourceCulture);
            }
        }
    }
}
